version: 2

updates:
  - package-ecosystem: dotnet-sdk
    target-branch: develop
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: 11:00
      timezone: Canada/Eastern
    commit-message:
      prefix: .NET SDK
    labels: [dependencies]
    assignees: [beauchama]

  - package-ecosystem: github-actions
    target-branch: develop
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: 11:00
      timezone: Canada/Eastern
    commit-message:
      prefix: GitHub Actions
    labels: [dependencies]
    assignees: [beauchama]
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: nuget
    target-branch: develop
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: 11:00
      timezone: Canada/Eastern
    commit-message:
      prefix: NuGet
    labels: [dependencies]
    assignees: [beauchama]
    groups:
      nugets:
        patterns:
          - '*'
