<Project>
  <PropertyGroup Label="Configure packages to be centralized">
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>

  <ItemGroup Label="Global analyzers">
    <GlobalPackageReference Include="AsyncFixer" Version="2.1.0" />
    <GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
    <GlobalPackageReference Include="Roslynator.Analyzers" Version="4.15.0" />
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.27.0.140913" />
  </ItemGroup>
</Project>
