<Project>
  <PropertyGroup Label="Configure packages to be centralized">
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>

  <ItemGroup Label="Global analyzers">
    <GlobalPackageReference Include="AsyncFixer" Version="2.1.0" />
    <GlobalPackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15" />
    <GlobalPackageReference Include="Roslynator.Analyzers" Version="4.15.0" />
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.25.0.139117" />
  </ItemGroup>

  <ItemGroup Label="Centralized package">
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="2.0.2" IncludeAssets="$(IncludedAssets)" PrivateAssets="all" />
  </ItemGroup>
</Project>
