<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))" />
  <ItemGroup Label="Test packages">
    <PackageVersion Include="TUnit" Version="1.53.0" IncludeAssets="$(IncludedAssets)" PrivateAssets="all" />
    <PackageVersion Include="TUnit.Mocks" Version="1.53.0" IncludeAssets="$(IncludedAssets)" PrivateAssets="all" />
    <PackageVersion Include="TUnit.Mocks.Assertions" Version="1.53.0" IncludeAssets="$(IncludedAssets)" PrivateAssets="all" />
    <PackageVersion Include="TUnit.Assertions.Should" Version="1.53.0-beta" IncludeAssets="$(IncludedAssets)" PrivateAssets="all" />
  </ItemGroup>
</Project>
