<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))" />
  <ItemGroup Label="Test packages">
    <PackageVersion Include="NSubstitute" Version="5.3.0" PrivateAssets="all" IncludeAssets="$(IncludedAssets)" />
    <PackageVersion Include="TUnit" Version="1.12.111" PrivateAssets="all" IncludeAssets="$(IncludedAssets)" />
  </ItemGroup>
</Project>
