//HintName: Event.g.cs
// <auto-generated/>
#nullable enable

using KappaDuck.Quack.Interop.SDL.Primitives.Events;

namespace KappaDuck.Quack.Events;

public readonly partial struct Event
{
    private readonly QuitRequestedEvent _quitRequestedEvent;

    private readonly SDL_EventType _type;

    /// <summary>
    /// Initializes a new instance holding a <see cref="QuitRequestedEvent"/>.
    /// </summary>
    /// <param name="e">The event value.</param>
    public Event(QuitRequestedEvent e)
    {
        _quitRequestedEvent = e;
        _type = SDL_EventType.Quit;
    }

    /// <summary>
    /// Gets a value indicating whether this event holds a value or not.
    /// </summary>
    public bool HasValue => _type == EventMapper.None;

    /// <summary>
    /// Gets the underlying value by boxing, or <see langword="null"/> if this event holds none.
    /// </summary>
    public object? Value => _type switch
    {
        SDL_EventType.Quit => _quitRequestedEvent,
        _ => null
    };

    /// <summary>
    /// Attempts to retrieve this event as a <see cref="QuitRequestedEvent"/>.
    /// </summary>
    /// <param name="e">The event value when this method returns <see langword="true"/>.</param>
    /// <returns><see langword="true"/> if this event holds a <see cref="QuitRequestedEvent"/>; otherwise <see langword="false"/>.</returns>
    public bool TryGetValue(out QuitRequestedEvent e)
    {
        if (_type != SDL_EventType.Quit)
        {
            e = default;
            return false;
        }

        e = _quitRequestedEvent;
        return true;
    }

}
