//HintName: EventMapper.g.cs
// <auto-generated/>
#nullable enable

using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using KappaDuck.Quack.Interop.SDL.Primitives.Events;

namespace KappaDuck.Quack.Events;

internal static partial class EventMapper
{
    private static readonly FrozenDictionary<Type, SDL_EventType> _map = new Dictionary<Type, SDL_EventType>
    {
        [typeof(QuitRequestedEvent)] = SDL_EventType.Quit,
    }.ToFrozenDictionary();

    internal static SDL_EventType Of<TEvent>() where TEvent : IEvent
        => _map.TryGetValue(typeof(TEvent), out SDL_EventType type) ? type : None;

    internal static Event Convert(in SDL_Event e) => e.Type switch
    {
        SDL_EventType.Quit => new QuitRequestedEvent(),
        _ => default
    };
}
