FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    pkg-config \
    mingw-w64 \
    ninja-build \
    gnome-desktop-testing \
    libasound2-dev \
    libpulse-dev \
    libaudio-dev \
    libfribidi-dev \
    libjack-dev \
    libsndio-dev \
    libx11-dev \
    libxext-dev \
    libxrandr-dev \
    libxcursor-dev \
    libxfixes-dev \
    libxi-dev \
    libxss-dev \
    libxtst-dev \
    libxkbcommon-dev \
    libdrm-dev \
    libgbm-dev \
    libgl1-mesa-dev \
    libgles2-mesa-dev \
    libegl1-mesa-dev \
    libdbus-1-dev \
    libibus-1.0-dev \
    libudev-dev \
    libthai-dev \
    libpipewire-0.3-dev \
    libwayland-dev \
    libdecor-0-dev \
    liburing-dev \
    libfreetype6-dev \
    libharfbuzz-dev \
    nasm \
    && rm -rf /var/lib/apt/lists/*

# Setup working directory
WORKDIR /src

# build args
ARG SDL3=release-3.2.28
ARG SDL3_Image=release-3.2.4
ARG SDL3_ttf=release-3.2.2

# Setup output directories
RUN mkdir -p runtimes/linux-x64/native runtimes/win-x64/native toolchains

# Build SDL3
RUN git clone --branch ${SDL3} --depth 1 https://github.com/libsdl-org/SDL.git

RUN cmake -S SDL -B SDL/build-linux \
    -DCMAKE_BUILD_TYPE=Release \
    && cmake --build SDL/build-linux --config Release \
    && cmake --install SDL/build-linux --config Release --prefix SDL/bin-linux \
    && strip SDL/bin-linux/lib/libSDL3.so.* \
    && cp -r SDL/bin-linux/lib/*.so* runtimes/linux-x64/native

RUN mkdir -p toolchains && \
    echo "SET(CMAKE_SYSTEM_NAME Windows)\n\
    SET(CMAKE_SYSTEM_PROCESSOR x86_64)\n\
    find_program(CMAKE_C_COMPILER NAMES x86_64-w64-mingw32-gcc REQUIRED)\n\
    find_program(CMAKE_CXX_COMPILER NAMES x86_64-w64-mingw32-g++ REQUIRED)\n\
    find_program(CMAKE_RC_COMPILER NAMES x86_64-w64-mingw32-windres windres REQUIRED)" \
    > toolchains/x86_64-w64-mingw32.cmake

RUN cmake -S SDL -B SDL/build-windows -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_TOOLCHAIN_FILE=../toolchains/x86_64-w64-mingw32.cmake \
    && cmake --build SDL/build-windows --config Release \
    && cmake --install SDL/build-windows --config Release --prefix SDL/bin-windows \
    && x86_64-w64-mingw32-strip SDL/bin-windows/bin/SDL3.dll \
    && cp -r SDL/bin-windows/bin/SDL3.dll runtimes/win-x64/native

# Build SDL3_image
RUN git clone --branch ${SDL3_Image} --depth 1 https://github.com/libsdl-org/SDL_image.git && SDL_image/external/download.sh

RUN cmake -S SDL_image -B SDL_image/build-linux \
    -DSDLIMAGE_VENDORED=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DSDL3_DIR=../SDL/bin-linux/lib/cmake/SDL3 \
    && cmake --build SDL_image/build-linux --config Release \
    && cmake --install SDL_image/build-linux --config Release --prefix SDL_image/bin-linux \
    && strip SDL_image/bin-linux/lib/libSDL3_image.so.* \
    && cp -r SDL_image/bin-linux/lib/*.so* runtimes/linux-x64/native

RUN cmake -S SDL_image -B SDL_image/build-windows -G Ninja \
    -DSDLIMAGE_VENDORED=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_TOOLCHAIN_FILE=../toolchains/x86_64-w64-mingw32.cmake \
    -DSDL3_DIR=../SDL/bin-windows/lib/cmake/SDL3 \
    && cmake --build SDL_image/build-windows --config Release \
    && cmake --install SDL_image/build-windows --config Release --prefix SDL_image/bin-windows \
    && x86_64-w64-mingw32-strip SDL_image/bin-windows/bin/SDL3_image.dll \
    && cp -r SDL_image/bin-windows/bin/*.dll runtimes/win-x64/native

# Build SDL3_ttf
RUN git clone --branch ${SDL3_ttf} --depth 1 https://github.com/libsdl-org/SDL_ttf.git && SDL_ttf/external/download.sh

RUN cmake -S SDL_ttf -B SDL_ttf/build-linux \
    -DSDLTTF_VENDORED=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DSDL3_DIR=../SDL/bin-linux/lib/cmake/SDL3 \
    && cmake --build SDL_ttf/build-linux --config Release \
    && cmake --install SDL_ttf/build-linux --config Release --prefix SDL_ttf/bin-linux \
    && strip SDL_ttf/bin-linux/lib/libSDL3_ttf.so.* \
    && cp -r SDL_ttf/bin-linux/lib/*.so* runtimes/linux-x64/native

RUN cmake -S SDL_ttf -B SDL_ttf/build-windows -G Ninja \
    -DSDLTTF_VENDORED=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_TOOLCHAIN_FILE=../toolchains/x86_64-w64-mingw32.cmake \
    -DSDL3_DIR=../SDL/bin-windows/lib/cmake/SDL3 \
    && cmake --build SDL_ttf/build-windows --config Release \
    && cmake --install SDL_ttf/build-windows --config Release --prefix SDL_ttf/bin-windows \
    && x86_64-w64-mingw32-strip SDL_ttf/bin-windows/bin/SDL3_ttf.dll \
    && cp -r SDL_ttf/bin-windows/bin/*.dll runtimes/win-x64/native
