<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Configuration">
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Experimental feature: https://github.com/dotnet/core/blob/main/release-notes/11.0/preview/preview1/runtime.md#runtime-async -->
    <Features>runtime-async=on</Features>
  </PropertyGroup>

  <PropertyGroup Label="Configure nupkg generation" Condition="$(Configuration) == 'Debug'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup Label="Make internals visible to test projects">
    <InternalsVisibleTo Include="Unit.Tests" />
    <InternalsVisibleTo Include="Integration.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KappaDuck.Quack.SourceGenerator\KappaDuck.Quack.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup Label="Global usings">
    <Using Include="KappaDuck.Quack.Interop" />
    <Using Include="KappaDuck.Quack.Interop.SDL" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="System.Runtime.CompilerServices" />
    <Using Include="System.Runtime.InteropServices" />
    <Using Include="System.Runtime.InteropServices.Marshalling" />
  </ItemGroup>

  <ItemGroup Label="Configure default search paths for DLL import">
    <AssemblyAttribute Include="System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute">
      <_Parameter1>SafeDirectories</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup Label="Packages">
    <PackageReference Include="DotNet.ReproducibleBuilds" />
    <PackageReference Include="KappaDuck.Quack.Runtimes" />
  </ItemGroup>

  <PropertyGroup Label="Quack! package metadata">
    <Authors>KappaDuck</Authors>
    <VersionPrefix>0.5.0</VersionPrefix>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <Company>@(Authors)</Company>
    <Copyright>Copyright © KappaDuck</Copyright>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <PackageIcon>icon.png</PackageIcon>
    <Description>Quack! is a modern, simple and fast multimedia framework for building games and interactive applications, built on top of SDL3 and its extensions (SDL_image, SDL_mixer, SDL_ttf). It targets .NET 11+ desktop and web apps, providing a clean and flexible API that hides the complexity of SDL.</Description>
    <PackageTags>NET;SDL;SDL3;GameEngine;Engine;CSharp;Game;Multimedia;GameFramework;MultimediaFramework</PackageTags>
  </PropertyGroup>

  <ItemGroup Label="Common files to include">
    <None Include="$(QuackRoot)$(PackageReadmeFile)" Pack="true" PackagePath="" Visible="false" />
    <None Include="$(QuackRoot)$(PackageLicenseFile)" Pack="true" PackagePath="" Visible="false" />
    <None Include="$(QuackRoot)$(PackageIcon)" Pack="true" PackagePath="" Visible="false" />
  </ItemGroup>
</Project>
