name: Staging

on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - 'KappaDuck.Quack/**'
      - 'global.json'
      - '.github/workflows/staging.yml'

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Build/Deploy
    runs-on: windows-latest
    env:
      QuackProject: KappaDuck.Quack\KappaDuck.Quack.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ./global.json

      - name: Install SDL dependencies
        run: dotnet .\SDL3\deps.cs

      - name: Restore dependencies
        run: dotnet restore ${{ env.QuackProject }}

      - name: Build
        run: dotnet build ${{ env.QuackProject }} --configuration release --no-restore

      - name: Package
        run: dotnet pack ${{ env.QuackProject }} --no-build --no-restore --output ./artifacts --version-suffix beta.${{ github.run_number }}

      - name: Publish to NuGet
        run: dotnet nuget push "**/*.nupkg" --source https://apiint.nugettest.org/v3/index.json --api-key ${{ secrets.NUGET_STAGING_API_KEY }} --skip-duplicate
