name: Staging

on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - 'src/KappaDuck.Quack/**'
      - '.github/workflows/staging.yml'

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Build/Deploy
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ./global.json

      - name: Get version
        shell: pwsh
        run: |
          $date = Get-Date -Format "yyyyMMddHHmmss"
          echo "date=$date" >> $env:GITHUB_ENV

      - name: Install SDL dependencies
        run: dotnet .\SDL3\deps.cs

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build KappaDuck.Quack\KappaDuck.Quack.csproj --configuration release --no-restore

      - name: Package
        run: dotnet pack KappaDuck.Quack\KappaDuck.Quack.csproj --no-build --no-restore --output ./artifacts --version-suffix alpha.${{ env.date }}

      - name: Publish to NuGet
        run: dotnet nuget push "**/*.nupkg" --source https://apiint.nugettest.org/v3/index.json --api-key ${{ secrets.NUGET_STAGING_API_KEY }} --skip-duplicate
