name: Update runtimes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 2'
      timezone: America/Toronto

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update:
    name: Check for updates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: ./global.json

      - name: Check for updates
        id: sdl
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: dotnet runtimes/scripts/update.cs

      - name: Create pull request
        if: steps.sdl.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          branch: dependency/sdl
          delete-branch: true
          add-paths: runtimes/utils/sdl.env
          commit-message: 'SDL: update runtime dependencies'
          title: 'SDL: update runtime dependencies'
          body-path: pr-body.md
          labels: dependencies
          assignees: beauchama
